export const listBks = [
  { id: 1, name: 'Royal Bank of Canada (RBC)' },
  { id: 2, name: 'Toronto-Dominion Bank (TD)' },
  { id: 3, name: 'Scotiabank' },
  { id: 4, name: 'Bank of Montreal (BMO)' },
  { id: 5, name: 'Canadian Imperial Bank of Commerce (CIBC)' },
  { id: 6, name: 'National Bank of Canada' },
  { id: 7, name: 'HSBC Bank Canada' },
  { id: 8, name: 'Desjardins Group' },
  { id: 9, name: 'Laurentian Bank of Canada' },
  { id: 10, name: 'Canadian Western Bank' },
  { id: 11, name: 'Manulife Bank of Canada' },
  { id: 12, name: 'ATB Financial' },
  { id: 13, name: 'EQ Bank' },
  { id: 14, name: 'Tangerine Bank' },
  { id: 15, name: 'First Nations Bank of Canada' },
  { id: 16, name: 'Bridgewater Bank' },
  { id: 17, name: 'Motus Bank' },
  { id: 18, name: 'Simplii Financial' },
  { id: 19, name: 'Wealth One Bank of Canada' },
  { id: 20, name: 'Concentra Bank' },
  { id: 21, name: 'Vancity Credit Union' },
  { id: 22, name: 'Meridian Credit Union' },
  { id: 23, name: 'Coast Capital Savings' },
  { id: 24, name: 'Servus Credit Union' },
  { id: 25, name: 'BlueShore Financial' },
  { id: 26, name: 'Innovation Credit Union' },
  { id: 27, name: 'Alterna Savings' },
  { id: 28, name: 'Steinbach Credit Union' },
  { id: 29, name: 'DUCA Credit Union' },
  { id: 30, name: 'Canadian Tire Bank' },
  { id: 31, name: "President's Choice Financial" },
  { id: 32, name: 'Peoples Trust Company' },
  { id: 33, name: 'Community Trust Company' },
  { id: 34, name: 'Home Trust Company' },
  { id: 35, name: 'RBC Dominion Securities' },
  { id: 36, name: 'TD Securities' },
  { id: 37, name: 'Scotia Capital' },
  { id: 38, name: 'BMO Nesbitt Burns' },
  { id: 39, name: 'CIBC Wood Gundy' },
  { id: 40, name: 'National Bank Financial' }
];
